version: "3"

networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
  admarket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "admarket"
    networks:
      - app-network
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env